### PR TITLE
pantilt function failed when passed negative values for pan_position …

### PR DESCRIPTION
**Pull request by TechnoSwiss**
…or tilt_position, fixed by taking 2s complement of number using boolean and with 0xFFFF

### CODE REVIEW

**Comment by misterhay** [comment]
I haven't encountered this issue, and I don't have a camera handy to test. @Yook74 can you take a look?

**Comment by RyanLehms** [comment]
@misterhay For what it's worth, I ran into this issue with a BirdDog A200 and this version of the code has resolved the problem for me. Not to mention, it's a lot more elegant than what I did to get around the problem:

`int(hex(int(negative_pan_value) & (2 ** 16 - 1)), 16)`

**Comment by Yook74** [comment]
The documentation clearly specifies the allowable range of values for `pan_position` and `tilt_position`. Depending on how you encode your negative value it may be outside of that range.

I like the change you've proposed, but I would prefer to raise `a ValueError` if the integer is larger than two bytes.

**Comment by TechnoSwiss** [comment]
Added a check that will raise a ValueError if an integer is passed that is larger than two bytes (signed).

**Comment by Yook74** [comment]
@TechnoSwiss so why did you want to specify a _signed_ integer? In my understanding, setting the camera to position 0x8000 will move it only slightly if the previous position was 0x7FFF. If the position was signed though that would cause it to go from one extreme to the other right?

**Comment by TechnoSwiss** [comment]
@Yook74 good question. I guess because the values I'm getting back from the get_pantilt_position function were signed values, and given the acceptable ranges given in the comments for pan and tilt, it appeared values should be signed. I probably should have been more specific to the limits on the input range since it's not just a 16-bit int, "Valid values are integers by default between 0x2200 and 0xDE00." for pan and "Valid values are integers 0x1200 to 0xFC00 if image flip is on or 0xEE00 to 0x400 if image flip is off." for tilt. Also my natural assumption with a pan/tilt mechanism would be for home to be zero, travel to move positive in one direction and negative in the other. (to be honest though I haven't actually verified that's the case with the protocol, or cameras I'm using)

**Comment by Yook74** [comment]
That's good reasoning, and I think you found a bug. My suspicion is that `get_pantilt_position` shouldn't be signed, but I'll check when next I have access to a camera. The speed parameters are kind of pseudo-signed. The sign is stripped off and encoded in the command separately in that case.

**Comment by Yook74** [comment]
I just made a new pull request #11 which fixes this bug. @TechnoSwiss you were right! Please take a look at #11 and see if it solves your problem.

**Comment by misterhay** [comment]
Thank you @TechnoSwiss for spotting the bug.

**Comment by TechnoSwiss** [comment]
> I just made a new pull request #11 which fixes this bug. @TechnoSwiss you were right! Please take a look at #11 and see if it solves your problem.

Yes that fixed the problem, thank you. Sorry for the late response I was out of town on business.

**Pull request closed without merging**
